### ISSUE TITLE
Google Drive transaction quota exceeded

### ISSUE THREAD

**Issue by mlgold** [bbrcan/zm2drive#3]
Google drive has a limit of 10 queries per second per IP address. This can be exceeded by deleting many files at once. I changed the delete code to be:

    if (args.deleteOld) {

      // delete files that exist on Drive, but not locally

      const zipFileNames = zipFiles.map(f => path.basename(f))

      //added
      const util = require('util');
      const sleep = util.promisify(setTimeout);
      //

      const filesToDelete = existingFiles
        .filter(f => !zipFileNames.includes(f.name))

      console.log(`Deleting ${filesToDelete.length} existing files.`)

      // Google drive has a quota of 10 transactions per second per IP address.
      // Wait 200 ms between deletes so a maximum of 5 delete transactions occur per second.
      filesToDelete.forEach(f => drive.deleteFile(f.id, auth), await sleep(200))
    }

and it seems to work.

**Comment by bbrcan** [comment]
Thanks mlgold, I've implemented your fix! :)

**Comment by mlgold** [comment]
200 ms does not seem to be enough if there are large numbers of files to delete. I am trying 500 ms and so far, so good. I requested more info about the quotas from Google, at third level support so far with no answer yet.

**Comment by mlgold** [comment]
Google's support was not helpful and provided no new information. Even waiting 500 ms between deletes, deleting more than 50 files still causes a quota exceeded error.

**Comment by mlgold** [comment]
It seems Google does not like it if 50 or more files are deleted within some period of time. So, I delete a maximum of 40 events for each new event seen.

This is my current code:

    if (args.deleteOld) {

      // delete files that exist on Drive, but not locally

      const zipFileNames = zipFiles.map(f => path.basename(f))

      //added
      const util = require('util');
      const sleep = util.promisify(setTimeout);
      //

      const filesToDelete = existingFiles
        .filter(f => !zipFileNames.includes(f.name))

      //deleted
      // console.log(`Deleting ${filesToDelete.length} existing files.`)

      //added
      const numDelFiles = Math.min(40,filesToDelete.length)
      console.log(`Deleting ${numDelFiles} existing files of ${filesToDelete.length} available to delete.`)

      // Google drive has a quota of 10 transactions per second per IP address and also does not
      // like more than 50 deletes, so limit the number of deletes to 40 and also
      // wait 250 ms between deletes so a maximum of 4 delete transactions occur per second.

      //deleted
      // filesToDelete.forEach(f => drive.deleteFile(f.id, auth), await sleep(500))

      //added
      for (let i = 0; i < numDelFiles; ++i) {
        drive.deleteFile(filesToDelete[i].id, auth)
        await sleep(250)
      }

    }

**Comment by mlgold** [comment]
Above code has worked with no issues, even when there are hundreds of files to delete.
